SELECT PRODUCT_CODE, SUM(SALES_AMOUNT * PRICE) AS SALES
    FROM PRODUCT
    INNER JOIN OFFLINE_SALE
        ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
    GROUP BY PRODUCT_CODE
    ORDER BY SALES DESC, PRODUCT_CODE ASC;
