SELECT YEAR(SALES_DATE) AS YEAR,
        MONTH(SALES_DATE) AS MONTH,
        GENDER,
        COUNT(DISTINCT INFO.USER_ID) AS USERS
    FROM ONLINE_SALE AS SALE
    INNER JOIN USER_INFO AS INFO
        ON SALE.USER_ID = INFO.USER_ID
    WHERE GENDER IS NOT NULL
    GROUP BY YEAR, MONTH, GENDER
    ORDER BY YEAR, MONTH, GENDER;
