WITH FRONT_END AS
(
    SELECT CODE
        FROM SKILLCODES
        WHERE CATEGORY = 'Front End'
)

SELECT DISTINCT PERS.ID, PERS.EMAIL, PERS.FIRST_NAME, PERS.LAST_NAME
    FROM DEVELOPERS AS PERS
    INNER JOIN FRONT_END AS FRONT
        ON PERS.SKILL_CODE & FRONT.CODE > 0
    ORDER BY PERS.ID;
    
