SELECT SALARY * MONTHS AS EARNING, COUNT(*)
    FROM EMPLOYEE
    GROUP BY EARNING
    ORDER BY EARNING DESC
    LIMIT 1;

/*
SELECT MAX(SALARY * MONTHS), COUNT(*)
    FROM EMPLOYEE
    WHERE SALARY * MONTHS IN (
        SELECT MAX(SALARY * MONTHS)
            FROM EMPLOYEE
    );
*/
