SELECT CAR.CAR_ID
    FROM (
        SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            GROUP BY CAR_ID
            HAVING MONTH(MAX(START_DATE)) = 10
    ) AS HISTORY
    INNER JOIN CAR_RENTAL_COMPANY_CAR AS CAR
        ON HISTORY.CAR_ID = CAR.CAR_ID
    WHERE CAR_TYPE = '세단'
    ORDER BY CAR.CAR_ID DESC;

/*
SELECT DISTINCT CAR.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
    INNER JOIN CAR_RENTAL_COMPANY_CAR AS CAR
        ON HISTORY.CAR_ID = CAR.CAR_ID
    WHERE CAR_TYPE = '세단'
        AND MONTH(START_DATE) = 10
    ORDER BY CAR.CAR_ID DESC;
*/
