SELECT ORDER_.PRODUCT_ID, PRODUCT_NAME, SUM(ORDER_.AMOUNT * PRODUCT.PRICE) AS TOTAL_SALES
    FROM FOOD_PRODUCT AS PRODUCT
    INNER JOIN (
                SELECT PRODUCT_ID, AMOUNT
                        FROM FOOD_ORDER
                        WHERE YEAR(PRODUCE_DATE) = 2022
                            AND MONTH(PRODUCE_DATE) = 5
                ) AS ORDER_
        ON PRODUCT.PRODUCT_ID = ORDER_.PRODUCT_ID
    GROUP BY ORDER_.PRODUCT_ID
    ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;
