SELECT BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY,
        SUM(PRICE * SALES) AS TOTAL_SALES
    FROM BOOK_SALES
    INNER JOIN BOOK
        ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
    INNER JOIN AUTHOR
        ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
    WHERE YEAR(SALES_DATE) = 2022
        AND MONTH(SALES_DATE) = 1
    GROUP BY BOOK.AUTHOR_ID, CATEGORY
    ORDER BY BOOK.AUTHOR_ID ASC, CATEGORY DESC;
