SELECT OUTS.ANIMAL_ID, OUTS.NAME
    FROM ANIMAL_OUTS AS OUTS
    INNER JOIN ANIMAL_INS AS INS
        ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
    WHERE OUTS.DATETIME < INS.DATETIME
    ORDER BY INS.DATETIME;
