SELECT MEMBER_NAME, REVIEW_TEXT,
        DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
    FROM (
        SELECT MEMBER_ID
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY COUNT(*) DESC
            LIMIT 1
    ) AS TARGET
    INNER JOIN REST_REVIEW
        ON TARGET.MEMBER_ID = REST_REVIEW.MEMBER_ID
    INNER JOIN MEMBER_PROFILE
        ON TARGET.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID
    ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;
