SELECT MEMBER_ID, MEMBER_NAME, GENDER,
       DATE(DATE_OF_BIRTH) AS DATE_OF_BIRTH
    FROM MEMBER_PROFILE
    WHERE GENDER = 'W'
          AND DATE_OF_BIRTH LIKE '%-03-%'
          AND TLNO is not null
    ORDER BY MEMBER_ID ASC;
