SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD AS BOARD
    INNER JOIN USED_GOODS_USER AS USER_
        ON BOARD.WRITER_ID = USER_.USER_ID
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
    ORDER BY TOTAL_SALES;
