SELECT OUTS.ANIMAL_ID, OUTS.NAME
    FROM ANIMAL_OUTS AS OUTS
    LEFT OUTER JOIN ANIMAL_INS AS INS
        ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
    WHERE INS.ANIMAL_ID IS NULL
    ORDER BY ANIMAL_ID;

/*
SELECT ANIMAL_ID, NAME
    FROM ANIMAL_OUTS
    WHERE (ANIMAL_ID, NAME) NOT IN
        (SELECT OUTS.ANIMAL_ID, OUTS.NAME
            FROM ANIMAL_OUTS AS OUTS
            INNER JOIN ANIMAL_INS AS INS
                ON OUTS.ANIMAL_ID = INS.ANIMAL_ID)
    ORDER BY ANIMAL_ID;
*/
