SELECT INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS,
        ROUND(AVG(REVIEW.REVIEW_SCORE), 2) AS SCORE
	FROM REST_INFO AS INFO
    INNER JOIN REST_REVIEW AS REVIEW
    	ON INFO.REST_ID = REVIEW.REST_ID
    WHERE ADDRESS LIKE '서울%'
    GROUP BY REST_ID
    ORDER BY SCORE DESC, FAVORITES DESC;
