SELECT CONCAT(NAME, '(', SUBSTR(OCCUPATION, 1, 1), ')') AS STR_
    FROM OCCUPATIONS
    ORDER BY STR_;

SELECT CONCAT('There are a total of ', COUNT(*), ' ', LOWER(OCCUPATION), 's.')
    FROM OCCUPATIONS
    GROUP BY OCCUPATION
    ORDER BY COUNT(*) ASC;
