WITH ROOTS (ITEM_ID) AS
(
    SELECT ITEM_ID
        FROM ITEM_TREE
        WHERE PARENT_ITEM_ID IS NULL
)

SELECT INFO.ITEM_ID, INFO.ITEM_NAME
    FROM ROOTS
    INNER JOIN ITEM_INFO AS INFO
        ON ROOTS.ITEM_ID = INFO.ITEM_ID
    ORDER BY INFO.ITEM_ID ASC;
