SELECT HALF.FLAVOR AS FLAVOR
    FROM (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
            FROM JULY
            GROUP BY FLAVOR
    ) AS JULY
    INNER JOIN FIRST_HALF AS HALF
        ON JULY.FLAVOR = HALF.FLAVOR
    ORDER BY JULY.TOTAL_ORDER + HALF.TOTAL_ORDER DESC
    LIMIT 3;
