WITH WANT_LANG AS
(
    SELECT CODE
        FROM SKILLCODES
        WHERE NAME IN ('Python', 'C#')
)

SELECT DISTINCT PER.ID, PER.EMAIL, PER.FIRST_NAME, PER.LAST_NAME
    FROM DEVELOPERS AS PER
    INNER JOIN WANT_LANG AS LANG
        ON PER.SKILL_CODE & LANG.CODE > 0
    ORDER BY PER.ID;