WITH RARE (ITEM_ID) AS
(
    SELECT ITEM_ID
        FROM ITEM_INFO
        WHERE RARITY = 'RARE'
)

SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY
    FROM (
        SELECT ITEM_TREE.ITEM_ID
            FROM RARE
            INNER JOIN ITEM_TREE
                ON RARE.ITEM_ID = ITEM_TREE.PARENT_ITEM_ID
    ) AS RARE_UPGRADED
    INNER JOIN ITEM_INFO
        ON RARE_UPGRADED.ITEM_ID = ITEM_INFO.ITEM_ID
    ORDER BY ITEM_ID DESC;
